INSERT INTO supplier (name, city, street, house, phone, email)
VALUES('Luettgen and Sons', 'South Evieview', 'Franecki Drive', 43, '716-905-5456 x198', 'Lindsay.Feeney1@hotmail.com'),
('Dicki Inc', 'East Dantefort', 'Santina Centers', 45, '563-548-2947 x7953', 'Aubree_Wehner@yahoo.com'),
('Stark, Schamberger and Runolfsdottir', 'New Noeshire', 'Nikko Summit', 179, '949.969.1819 x99905', 'Angel.Larkin@gmail.com'),
('Hammes Inc', 'Merlberg', 'Graham Branch', 191, '629-967-6469 x35082', 'Dorthy_Lueilwitz@hotmail.com'),
('Lehner, Heller and Harvey', 'Ratkeview', 'Dickinson Port', 39, '963.100.2657', 'Gussie.Nitzsche48@yahoo.com'),
('Mohr - Kuhn', 'Cristobalstad', 'Hettinger Overpass', 168, '764-596-7239', 'Edwina17@gmail.com'),
('Ankunding, McDermott and Fritsch', 'Candidafurt', 'Meggie Harbor', 53, '068.199.3620 x87405', 'Roberto.Bednar57@yahoo.com'),
('Roberts Group', 'New Elmoshire', 'Brent Mill', 85, '268.879.8030 x107', 'Lauryn.Kihn69@yahoo.com'),
('Schiller, Blick and Dickens', 'Robertsborough', 'Cummerata Lake', 109, '278.759.4301', 'Rubie59@yahoo.com'),
('Eichmann, Lowe and Barrows', 'Heidenreichfurt', 'Kutch Roads', 85, '299-083-1332 x7398', 'Gavin27@hotmail.com');

INSERT INTO registration_product (information, waybill, requisites, supplier_id)
VALUES('Sunt commodi nisi.', 20, 'Intuitive bifurcated extranet', 9),
('Ipsum aut voluptate.', 934, 'Quality-focused heuristic website', 9),
('Dolorem laboriosam magnam.', 215, 'Compatible methodical circuit', 3),
('Voluptatem laudantium corporis nihil.', 646, 'Pre-emptive interactive framework', 4),
('Quas in aut expedita earum necessitatibus ut officiis debitis voluptatem.', 943, 'Secured background website', 10),
('Quis ea natus nulla molestiae fuga assumenda sint.', 963, 'Grass-roots zero defect analyzer', 8),
('Soluta minus rerum eum.', 573, 'Cross-platform directional local area network', 10),
('Perferendis recusandae omnis eius rerum facilis doloribus.', 238, 'Reduced cohesive open architecture', 3),
('Perferendis error blanditiis minima autem consequuntur voluptatem dolorem unde dolores.', 794, 'Profit-focused transitional solution', 4),
('Aliquid quibusdam veniam velit dolor non omnis repudiandae architecto sint.', 638, 'Team-oriented attitude-oriented ability', 7),
('Id corrupti ullam.', 175, 'Universal national success', 6),
('Accusantium sunt ducimus harum praesentium itaque doloribus maxime et.', 927, 'Assimilated zero administration utilisation', 10),
('Mollitia similique placeat sapiente quia suscipit tempore autem.', 664, 'Adaptive real-time circuit', 7),
('Consequatur aperiam eos et et minus quos asperiores in fugiat.', 431, 'Enterprise-wide client-driven project', 8),
('Illum reprehenderit ex.', 379, 'Open-architected uniform knowledge user', 2),
('Voluptatem dolor dolores soluta maiores.', 429, 'User-centric content-based conglomeration', 8),
('Qui totam repellendus natus omnis.', 131, 'Up-sized optimal customer loyalty', 2),
('Quo corporis sunt voluptatem officia et saepe nobis.', 708, 'Persevering demand-driven groupware', 3),
('Blanditiis tempore voluptatum nihil est voluptates.', 995, 'Innovative 4th generation internet solution', 8),
('Impedit vel aut recusandae aut.', 608, 'Progressive value-added contingency', 3);
